### ISSUE TITLE
Improvement to package loading instructions

### ISSUE THREAD

**Issue by AndrewSwann** [dholm/benchmark-init-el#7]
This is just a comment on improving the suggested method of loading the code when installed via el-get or the package manager.  Currently the README suggests

```
(let ((benchmark-init.el "/path/to/el-get/benchmark-init/benchmark-init.el"))
  (when (file-exists-p benchmark-init.el)
    (load benchmark-init.el)))
```

however the `load` function has options to not report an error if the file exists.  Also by default it will start by trying to add extensions `.elc` and `.el` to the file name.  I suggest you shorten the code to

```
(let ((benchmark-init-el "/path/to/el-get/benchmark-init/benchmark-init.el")
  (load benchmark-init-el 'no-error nil 'no-suffix))
```

or even to a single `load` statement

```
(load "/path/to/el-get/benchmark-init/benchmark-init.el"
  'no-error nil 'no-suffix)
```

**Comment by dholm** [comment]
@AndrewSwann Thanks, documentation fixed!
