### ISSUE TITLE
Makefile missing, benchmark-init-loaddefs.el not created

### ISSUE THREAD

**Issue by dbitouze** [dholm/benchmark-init-el#8]
I installed `benchmark-init` thanks to ELPA and, AFAICS, it has been put in `~/.emacs.d/elpa/benchmark-init-20150905.238`:

```bash
$ ls -1  ~/.emacs.d/elpa/benchmark-init-20150905.238
benchmark-init-autoloads.el
benchmark-init.el
benchmark-init.elc
benchmark-init-modes.el
benchmark-init-modes.elc
benchmark-init-pkg.el
```

But, the `Makefile` is missing. If I add it manually:
```bash
$ make
make: nothing to do for « all ».
```
but no `benchmark-init-loaddefs.el` file produced.

**Comment by dholm** [comment]
I think ELPA creates `benchmark-init-autoloads.el` instead.  I have updated the readme to describe how to install via ELPA.
